---
Name: silvershop-payway
After:
  - '#shopconfig'
---

# extensions
Injector:
  OnsitePaymentCheckoutComponent:
    class: PaywayPaymentCheckoutComponent

Member:
  extensions:
    - PaywayMemberExtension

Order:
  extensions:
    - PaywayOrderExtension
  # available payment frequencies
  payment_frequency:
    once: Once
    # monthly: Monthly
    # yearly: Annually

ShopAccountForm:
  extensions:
    - PaywayShopAccountFormExtension


# payment
GatewayInfo:
  PaywayRest:
    parameters:
      apiLinkCreditCardForm: https://api.payway.com.au/rest/v1/creditCardForm.js
      # apiKeyPublic: PUBLISHABLE-API-KEY
      # apiKeySecret: SECRET-API-KEY
      # merchantId: TEST
  PaywayRest_DirectDebit:
    parameters:
      apiLinkBankAccountForm: https://api.payway.com.au/rest/v1/bankAccountForm.js
      # apiKeyPublic: PUBLISHABLE-API-KEY
      # apiKeySecret: SECRET-API-KEY
      # bankAccountId: 0000000A
